mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: false
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: dashboard/dist
tcp-concurrent: true
interface-name: ""
enable-process: false
geodata-loader: memconservative
secret: ""
sniffer:
  enable: false
  sniffing:
    - tls
    - http
  force-domain:
    - '+'
  skip-domain:
    - 'google.com'
  port-whitelist:
    - 80
    - 443
    - 8000-9000
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  device: Meta
  ipv6: false
  default-nameserver: 
    - 8.8.8.8
    - 1.1.1.1
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['networktest.twilio.com', '+.twilio.com']
  nameserver:
    - 1.1.1.1
    # ISI IP BUG YANG KALIAN GUNAKAN 
  proxy-server-nameserver:
    - 1.0.0.1
    # ISI IP BUG YANG KALIAN GUNAKAN 
  fallback: []
  fallback-filter:
    geoip: false
    geoip-code: 'ID'
    geosite:
      - GFW
      - GREATFIRE
    domain: ['google.com']
    ipcidr: [240.0.0.0/4]
tun:
  enable: false
  device: Meta
  stack: gvisor
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: false
  auto-detect-interface: false
iptables: {enable: false, inbound-interface: "", bypass: []}
hosts:
  'note.microsoft.com': 104.18.38.174
  'maps.google.com': 104.18.10.39
geox-url:
  mmdb: "https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb"
  geoip: "https://github.com/v2fly/geoip/raw/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat"
tproxy-port: 9898
proxies:
proxy-providers:
  VMESS:
    type: file
    path: "./Vmess.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 100
  VLESS:
    type: file
    path: "./Vless.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 100
  TROJAN:
    type: file
    path: "./Trojan.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 100
  SHADOWSOCKS:
    type: file
    path: "./Shadowsocks.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 100
proxy-groups:
- name: ğŸ’€ZHE-CONFIGURATIONğŸ’€
  type: select
  proxies:
    - ğŸˆµALL-SERVER-BESTğŸˆµ
    - ğŸ‘¨ğŸ»â€ğŸ’»VMESSğŸ‘¨ğŸ»â€ğŸ’»
    - ğŸ‘½VLESSğŸ‘½
    - ğŸ‘¾TROJANğŸ‘¾
    - â˜£ï¸SHADOWSOCKSâ˜£ï¸
    - ğŸ‘¨ğŸ»â€ğŸ’»VMESS-BESTğŸ‘¨ğŸ»â€ğŸ’»
    - ğŸ‘½VLESS-BESTğŸ‘½
    - ğŸ‘¾TROJAN-BESTğŸ‘¾
    - â˜£ï¸SHADOWSOCKS-BESTâ˜£ï¸
    - ğŸ‘¨ğŸ»â€ğŸ’»VMESS-LOADBALANCEğŸ‘¨ğŸ»â€ğŸ’»
    - ğŸ‘½VLESS-LOADBALANCEğŸ‘½
    - ğŸ‘¾TROJAN-LOADBALANCEğŸ‘¾
    - â˜£ï¸SHADOWSOCKS-LOADBALANCEâ˜£ï¸
    - ğŸ‘¨ğŸ»â€ğŸ’»VMESS-FALLBACKğŸ‘¨ğŸ»â€ğŸ’»
    - ğŸ‘½VLESS-FALLBACKğŸ‘½
    - ğŸ‘¾TROJAN-FALLBACKğŸ‘¾
    - â˜£ï¸SHADOWSOCKS-FALLBACKâ˜£ï¸

- name: ğŸˆµALL-SERVER-BESTğŸˆµ
  type: url-test
  tolerance: 50
  use:
  - VMESS
  - VLESS
  - TROJAN
  - SHADOWSOCKS
- name: ğŸ‘¨ğŸ»â€ğŸ’»VMESSğŸ‘¨ğŸ»â€ğŸ’»
  type: select
  use:
  - VMESS
- name: ğŸ‘½VLESSğŸ‘½
  type: select
  use:
  - VLESS
- name: ğŸ‘¾TROJANğŸ‘¾
  type: select
  use:
  - TROJAN
- name: â˜£ï¸SHADOWSOCKSâ˜£ï¸
  type: select
  use:
  - SHADOWSOCKS

- name: ğŸ‘¨ğŸ»â€ğŸ’»VMESS-BESTğŸ‘¨ğŸ»â€ğŸ’»
  type: url-test
  tolerance: 100
  use:
  - VMESS
- name: ğŸ‘½VLESS-BESTğŸ‘½
  type: url-test
  tolerance: 100
  use:
  - VLESS
- name: ğŸ‘¾TROJAN-BESTğŸ‘¾
  type: url-test
  tolerance: 100
  use:
  - TROJAN
- name: â˜£ï¸SHADOWSOCKS-BESTâ˜£ï¸
  type: url-test
  tolerance: 100
  use:
  - SHADOWSOCKS

- name: ğŸ‘¨ğŸ»â€ğŸ’»VMESS-LOADBALANCEğŸ‘¨ğŸ»â€ğŸ’»
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - VMESS
- name: ğŸ‘½VLESS-LOADBALANCEğŸ‘½
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - VLESS
- name: ğŸ‘¾TROJAN-LOADBALANCEğŸ‘¾
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - TROJAN
- name: â˜£ï¸SHADOWSOCKS-LOADBALANCEâ˜£ï¸
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - SHADOWSOCKS

- name: ğŸ‘¨ğŸ»â€ğŸ’»VMESS-FALLBACKğŸ‘¨ğŸ»â€ğŸ’»
  type: fallback
  url: http://hi.bonds.id/ping
  interval: 300
  use:
  - VMESS  
- name: ğŸ‘½VLESS-FALLBACKğŸ‘½
  type: fallback
  url: http://hi.bonds.id/ping
  interval: 300
  use:
  - VLESS  
- name: ğŸ‘¾TROJAN-FALLBACKğŸ‘¾
  type: fallback
  url: http://hi.bonds.id/ping
  interval: 300
  use:
  - TROJAN  
- name: â˜£ï¸SHADOWSOCKS-FALLBACKâ˜£ï¸
  type: fallback
  url: http://hi.bonds.id/ping
  interval: 300
  use:
  - SHADOWSOCKS  

rule-providers:
  Vmess:
    type: http
    behavior: classical
    path: "./Vmess.yaml"
    url: https://raw.githubusercontent.com/dhedy09/akunAs/main/Vmess.yaml
    interval: 86400
  Vless:
    type: http
    behavior: classical
    path: "./Vless.yaml"
    url: https://raw.githubusercontent.com/dhedy09/akunAs/main/Vless.yaml
    interval: 86400
  trojan:
    type: http
    behavior: classical
    path: "./Trojan.yaml"
    url: https://raw.githubusercontent.com/dhedy09/akunAs/main/Trojan.yaml
    interval: 86400
  Shadowsocks:
    type: http
    behavior: classical
    path: "./Shadowsocks.yaml"
    url: https://raw.githubusercontent.com/dhedy09/akunAs/main/Shadowsocks.yaml
    interval: 86400    

rules:
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve
  - MATCH,ğŸ’€ZHE-CONFIGURATIONğŸ’€
